site_name: numerous-widgets docs
nav:
  - Home: README.md
  - Our Website: https://numerous.com
  - Our GitHub Page: https://github.com/numerous-com/numerous-widgets
  - Our PyPI Page: https://pypi.org/project/numerous-widgets/
  - Platform Docs: https://numerous.com/docs
  - API Reference:
    - Widgets: widgets.md
    - Process Task: process_task.md
    

theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: "python"
      handlers:
        python:
          paths: [.]
          import:
            - https://docs.python.org/3/objects.inv
          rendering:
            show_source: true
            show_full_signature: true
            show_root_heading: true
